name: CI Pipeline

on:
  push:
    # branches:
    #   - main
    #   - develop

jobs:

  run-shell-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Echo a String
        run: echo "Hello World"

      - name: Multiline Command
        run: |
          node -v
          npm -v

  parallel-jobs:
    runs-on: ubuntu-latest

    steps:
      - name: Print Current Directory
        run: pwd

  dependent-jobs:
    runs-on: ubuntu-latest

    needs:
      - run-shell-commands
      - parallel-jobs

    steps:
      - name: Check Docker Version
        run: docker --version


        
            # - name: Checkout source code
            #   uses: actions/checkout@v4

            # - name: Setu up Node.js
            #   uses: actions/setup-node@v4
            #   with:
            #     node-version: '20'
            # - name: Install depedencies
            #   run: npm ci
            # - name: Run tests
            #   run: npm test
            # - name: build application
            #   run: npm run build